# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "circleci-project-setup" branch
  push:
    branches: [ "circleci-project-setup" ]
  pull_request:
    branches: [ "circleci-project-setup" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: response
        run: |
         echo Hello, world!
         echo ${{ github.ref_name }}
         Branch="test/branch/name"
         echo "TAG=${Branch////_}"
         echo ${{ github.event.head_commit.message }}
         echo ${{ github.event.repository.name }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: "Mail Output"
        uses: cinotify/github-action@main
        with:
          to: 'ahkfxyv@gmail.com'
          subject: 'building main'
          body: 'Body with version-update:${{ steps.response.outputs.result }}'
