# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "circleci-project-setup" branch
  push:
    branches: [ "circleci-project-setup" ]
  pull_request:
    branches: [ "circleci-project-setup" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      ecr_image_tag:
        description: "ECR image tag to deploy"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        id: work_done
        run: |
         echo ${{ github.ref_name }}
         Branch="test/branch/name"
         echo "TAG=${Branch////_}"
         echo ${{ github.event.head_commit.message }}
         echo ${{ github.event.repository.name }}
         echo ${{ steps.login-ecr.outputs.registry }}
         
      - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          card-layout-start: compact
          card-layout-exit: complete
          show-on-start: false
          show-on-exit: true
          show-on-failure: true
         
      - name: Store Plan Output
        id: response
        run: |
          echo "::set-output name=my_output::hello----"
          echo "${{ github.event.inputs.ecr_image_tag }}"

        
      # Runs a set of commands using the runners shell


      # - name: "Mail Output"
      #   run: |
      #     sudo apt-get install mailutils
      #     echo "Body with version-update:Hello, world" | mail -s "Successfully pushed to main" ahkfxyv@gmail.com
